version: '3.8'

services:
  transport-te-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transport-te-api-prod
    ports:
      - "8400:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__chaine=Server=192.168.2.118;Database=GUOT_TE_PROD;User ID=msuser;Password=9$SViSWexRn5hWq;Connect Timeout=30;Encrypt=False;Trust Server Certificate=True;
    restart: unless-stopped
